In [1]:
import os

if not {"word2vec.model", "word2vec.model.vectors.npy"}.issubset(set(os.listdir())):
    # Get the pretrained Google Word2Vec dataset
    # This might take a couple minutes
    print("Downloading Google word2vec dataset...")

    import gensim.downloader
    wv = gensim.downloader.load("word2vec-google-news-300")
    wv.save("./word2vec.model")

    print("Download complete.")

print("File Exists")

from gensim.models import KeyedVectors
wv = KeyedVectors.load("word2vec.model", mmap="r")
print(wv)

File Exists
KeyedVectors<vector_size=300, 3000000 keys>


In [2]:
import numpy as np

x = []
for i in range(300):
    x.append(wv[i])
    # if (i == 100000):
    #     print("hi")
    # if (i == 1000000):
    #     print("hi")
x = np.asarray(x)

# x = np.array([])
# for i in range(300):
#     x = np.append(x, wv[i])
#     print(x[i][0], end = " ")
# print(x.shape)


In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import decomposition

In [30]:
maxTransform = np.asarray([[], [], [], []])
maxNum = 0

def dataAnalysis(dim, data):
    global maxTransform, maxNum
    if maxNum > dim:
        #going to be problematic b/c list not array
        #need slice method to work b/c constant time
        return maxTransform[:, dim]

    else:
        newDim = dim - maxNum

        arr2 = data[ : , newDim : data[0].__len__() ]
        pca = decomposition.PCA(n_components = newDim)
        pca.fit(arr2)
        arr2 = np.asarray(pca.transform(arr2))
        #maybe have to transpose this back ??
        #before running it

        print(type(maxTransform))

        maxTransform2 = maxTransform.tolist()
        arr3 = arr2.tolist()
        
        print("after list")
        print(maxTransform2)
        print(arr3)

        # arr3 = arr2.tolist()
        np.transpose(maxTransform2)
        np.transpose(arr3)
        maxTransform2 = np.append(maxTransform2, arr3, 1)
        np.transpose(maxTransform2)

        print("after transpose")
        print(maxTransform2)
        print(arr3)

        #wait so obviously .append() doesn't work
        # we want to append the individual elements of the vector for the new decomposition to the old vector in max transform
        # not add new vectors
        # therefore, .append doesn't work
        # maxTransform2.append(arr3)
        # print(maxTransform2)
        # print(arr3)

        #maybe be creative about it. TRANSPOSE THE MATRIX AND THEN APPENDING SHOULD WORK! 
        #and bc it's transposed, swap axes is all.

        print(type(maxTransform2))
        print(type(arr2))
        print("Max Transform # of vectors " + str(maxTransform2.__len__()))
        print("Max Transform Size of vectors " + str(maxTransform2[0].__len__()))
        #number of vectors is becoming 2 cause the variable is global and append works the second time around
        #size of vectors is still 300 weirdly??

        maxNum = dim
        return maxTransform2

    #sort the components in the order of necessity and then truncate to a few !!!

    #pca.transform() mid
    #basically store largest array, truncate if amt is <
    #and then also use current components 

    #binsearch
    #if 'playable' - run function - then halt search
    #call data analysis on dim indefinite with given data

#setting up plot
#data collection
x = np.array([[1, 2, 3, 4, 5], [2, 1, 3, 3, 1], [2, 4, 1, 2, 3], [4, 3, 2, 1, 4]])
print(dataAnalysis(2, x))
print(dataAnalysis(3, x))
print(dataAnalysis(2, x))

# m = findDim(x)
# visualize(m, x)

#print("check1")
#actual decomposition
#len(x[0]) = upper bound
#print("check2")
#visualize(dimensions, x)
#print("check3")
#plt.plot(x)
#plot is an additional plot (like the add subplot is unnecessary): reason for issue: was overriding previous plot
#however this is merely adding the terms
#need to display pca on plt

#math ee - perhaps describe how to do it with gradient function and the like to pick a random dimension
#instead of going down one dimension at a time


<class 'numpy.ndarray'>
after list
[[], [], [], []]
[[-1.9567557240022286, -1.4282101101440268], [2.1436820249639488, -1.1109164432822658], [0.33961794239715837, 1.0664928435531646], [-0.5265442433588783, 1.4726337098731281]]
after transpose
[[-1.95675572 -1.42821011]
 [ 2.14368202 -1.11091644]
 [ 0.33961794  1.06649284]
 [-0.52654424  1.47263371]]
[[-1.9567557240022286, -1.4282101101440268], [2.1436820249639488, -1.1109164432822658], [0.33961794239715837, 1.0664928435531646], [-0.5265442433588783, 1.4726337098731281]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Max Transform # of vectors 4
Max Transform Size of vectors 2
[[-1.95675572 -1.42821011]
 [ 2.14368202 -1.11091644]
 [ 0.33961794  1.06649284]
 [-0.52654424  1.47263371]]
<class 'numpy.ndarray'>
after list
[[], [], [], []]
[[0.2266807355150663], [2.6669463578870745], [-1.471053065808461], [-1.4225740275936798]]
after transpose
[[ 0.22668074]
 [ 2.66694636]
 [-1.47105307]
 [-1.42257403]]
[[0.2266807355150663], [2.666946357887

IndexError: index 2 is out of bounds for axis 1 with size 0

In [ ]:
def visualize(dim, data):
    #data = np.array(data)
    if dim == 3 or dim == 2:
        fig = plt.figure()
        plt.clf()

        if dim == 3:
            ax = fig.add_subplot(projection = "3d") #this is rectilinear, 3d, etc. projection= "3d"
        elif dim == 2:
            ax = fig.add_subplot(projection = "rectilinear")
        
        ax.set_position([0, 0, 0.95, 1])
        plt.cla()

        if dim == 3:
            ax.scatter(data[:, 0], data[:, 1], data[:, 2])
        elif dim == 2:
            ax.scatter(data[:, 0], data[:, 1])

        
        plt.show()
    else:
        print("Too many/too few dimensions to visualize")
        ans = "n"
        #ans = input("Proceed with 2-D? y/n")
        if ans == "y":
            fig = plt.figure(figsize=(5 * dim, 5 * dim))
            fig.subplots_adjust(hspace=0.4, wspace=0.4)
            for i in range(dim):
                for j in range(i+1, dim):
                    ax2 = fig.add_subplot(dim, dim-1, (i+1)*(j+1))
                    ax2.scatter(z[:, i], z[:, j])
            plt.show()

        #https://matplotlib.org/stable/api/projections_api.html#module-matplotlib.projections

In [ ]:
def playable(dim, data):
    y = dataAnalysis(dim, data)
    # print("size" + str(y[0].__len__()))
    # print("length" + str(y.__len__()))
    #figure out AI later
    #maybe instead of coding ai, all I have to do is check number of words with similarity value 
    #biggest similarity
    #smallest similarity
    #level of variance?
    #number of words with distance d away from starting word
    #want to preserve distance, too
    if dim == 2:
        return True
    else:
        return False

In [ ]:
def findDim(data, start=1, end=300):
    print(start)
    print(end)
    if start >= end:
        return end
    else:
        mid = (start + end)//2
        if not playable(mid, data):
            return findDim(data, mid + 1, end)
        else:
            return findDim(data, start, mid-1)

In [ ]:
# z = dataAnalysis(2, x)
# visualize(2, z)

# z = dataAnalysis(3, x)
# visualize(3, z)

#z = dataAnalysis(4, x)

# fig = plt.figure()
# fig.subplots_adjust(hspace=0.4, wspace=0.4)
# for i in range(1, 7):
#     ax = fig.add_subplot(2, 3, i)
#     ax.text(0.5, 0.5, str((2, 3, i)),
#            fontsize=18, ha='center')


#kjflkajwrklwejr first grid in top row is same as 2-D grid! proves pca transform is consistent